services:
  - type: web
    name: rekroot-server
    runtime: node
    rootDir: SERVER
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
